### ISSUE TITLE
Why it's disabled for touch devices?

### ISSUE THREAD

**Issue by andrey-hohlov** [kasparsj/jquery-easy-parallax#1]
It's my first use this plugin and i think it's great. Thank you!

But why plugin disabled for touch devices? I have remove this condition and test on iPad Mini 2 (iOS 9) - and it works!

**Comment by inweb-pro** [comment]
> But why plugin disabled for touch devices? I have remove this condition

Hello, andrey! How do you remove this condition for touch devices?
P.S. одним словом как заставить работать на мобильных и отключить проверку?
интересно также как обстоят дела с Android

**Comment by kasparsj** [comment]
Thanks guys for reporting. Added enableTouchDevices options:
https://github.com/kasparsj/jquery-data-parallax#global-options
https://github.com/kasparsj/jquery-data-parallax#enabletouchdevices
