### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by nam-co** [kasparsj/jquery-easy-parallax#4]
Hi Kaspars, thanks for this cool package, I was wondering if still active in development and if your planing on putting it in npm?

Thanks for your time

**Comment by nam-co** [comment]
https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by kasparsj** [comment]
Thanks, should be fixed now.

**Comment by nam-co** [comment]
Thanks Kaspars, thanks for sharing

K one question, is it possible to activate parallax in mobile?

**Comment by kasparsj** [comment]
Yes: https://github.com/kasparsj/jquery-data-parallax#enabletouchdevices-1
